[versions]

# general
lombok = "1.18.42"
jar-relocator = "1.9"
maven-resolver = "1.9.18"
resolver-slf4j = "1.7.36"
shadow = "9.3.0"
toolkit = "dev-a4c6f1b"
jetbrains-annotations = "26.0.2"
junit = "6.0.0"

# platforms apis
bungee = "26.1-R0.1-SNAPSHOT"
bukkit = "26.1.2-R0.1-SNAPSHOT"
paper = "26.1.2.build.63-stable"
velocity = "3.4.0-SNAPSHOT"

# platforms apis -> spring
spring-boot = "4.0.1"
slf4j = "2.0.16"
assertj = "3.27.6"

[libraries]

shadow = { group = "com.gradleup.shadow", name = "shadow-gradle-plugin", version.ref = "shadow" }
toolkit-architecture = { group = "me.whereareiam.toolkit", name = "architecture", version.ref = "toolkit" }

maven-resolver-impl = { group = "org.apache.maven.resolver", name = "maven-resolver-impl", version.ref = "maven-resolver" }
maven-resolver-supplier = { group = "org.apache.maven.resolver", name = "maven-resolver-supplier", version.ref = "maven-resolver" }
resolver-slf4j-nop = { group = "org.slf4j", name = "slf4j-nop", version.ref = "resolver-slf4j" }

# general
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
jar-relocator = { group = "me.lucko", name = "jar-relocator", version.ref = "jar-relocator" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations" }

# junit
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit" }

# platform apis
bungee = { group = "net.md-5", name = "bungeecord-api", version.ref = "bungee" }
bukkit = { group = "org.spigotmc", name = "spigot-api", version.ref = "bukkit" }
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }

# platform apis -> spring
spring-boot-autoconfigure = { group = "org.springframework.boot", name = "spring-boot-autoconfigure", version.ref = "spring-boot" }
spring-boot-configuration-processor = { group = "org.springframework.boot", name = "spring-boot-configuration-processor", version.ref = "spring-boot" }
spring-boot-test = { group = "org.springframework.boot", name = "spring-boot-test", version.ref = "spring-boot" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
assert4j-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }

[plugins]
toolkit-architecture = { id = "me.whereareiam.toolkit.architecture", version.ref = "toolkit" }
toolkit-versioning = { id = "me.whereareiam.toolkit.versioning", version.ref = "toolkit" }
