[versions]

# general
lombok = "1.18.42"
jar-relocator = "1.9"
jetbrains-annotations = "26.0.2"
junit = "6.0.0"

# platforms apis
bukkit = "1.21.10-R0.1-SNAPSHOT"
paper = "1.21.10-R0.1-SNAPSHOT"
velocity = "3.4.0-SNAPSHOT"

[libraries]

# general
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
jar-relocator = { group = "me.lucko", name = "jar-relocator", version.ref = "jar-relocator" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations" }

# junit
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit" }

# platform apis
bukkit = { group = "org.spigotmc", name = "spigot-api", version.ref = "bukkit" }
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }

